<a href="https://colab.research.google.com/github/donakwale2020/Gitexample1/blob/master/numpyexam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
print(time.ctime())

Wed Jul 20 19:16:18 2022


In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import os
if 'COLAB_TPU_ADDR' not in os.environ:
  print('Not connected to TPU')
else:
  print('connected to TPU')

connected to TPU


In [ ]:
%pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import files
upload=files.upload()

Saving DevNet SPSS Datasets.xlsx to DevNet SPSS Datasets.xlsx


In [ ]:
import numpy as np
arr=[4,6,7,8]
print(type(arr))


<class 'list'>


In [ ]:
a=np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
(4,)
int64
1


In [ ]:
print(4*3^2)

14


In [ ]:
import numpy as np
np.random.random((2,3))

array([[0.98752077, 0.39920585, 0.50928221],
       [0.92854729, 0.81107352, 0.68909697]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
import numpy as np

In [4]:
c=np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [5]:
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [6]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [7]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [8]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [10]:
arr=[6,7,8,9]

In [11]:
a=np.array(arr)

In [12]:
b=np.array([[1,2,3],[4,5,6]])

In [14]:
a[0]


6

In [15]:
a[3]

9

In [16]:
b[0,1]

2

In [17]:
b[1,2]

6

In [18]:
c[0,1]

8.0

In [19]:
d[1, 0:2]

array([9., 8.])

In [21]:
e=np.array([[10,11,12],[13,14,15],
          [16,17,18],[19,20,21]])

In [24]:
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [28]:
e[:4,:1]

array([[10],
       [13],
       [16],
       [19]])